###
###
# @name login

POST http://localhost:8080/api/user/login
accept: application/json
content-type: application/json

{
  "panNo": "2108937138904723",
  "password": "test"
}

###

POST http://localhost:8080/api/trade/add
accept: application/json
content-type: application/json

{
  "userId": "67a8b3cc034cd653f080fecb",
  "access_token": "{{login.response.body.$.accessToken}}",
  "nob": "Aklsdj",
  "totalAmount": 1900,
  "desc": "alsdjh;askdjhalskdhjasdlh",
  "panNo": "2108937138904723",
  "phases": [
    {
      "phase": 1,
      "amount": 300
    },
    {
      "phase": 2,
      "amount": 200
    }
  ]
}
###
