###
# @name login1

POST http://localhost:8080/api/user/login
accept: application/json
content-type: application/json

{
  "panNumber": "2108937138904723",
  "password": "test"
}

###
# @name login2

POST http://localhost:8080/api/user/login
accept: application/json
content-type: application/json

{
  "panNumber": "1234564789",
  "password": "test2"
}

###

POST http://localhost:8080/api/trade/add
accept: application/json
content-type: application/json
cookie: access_token={{login1.response.body.$.accessToken}}

{
  "nob": "Sidewinder Inv",
  "totalAmount": 20000,
  "desc": "Tealsjdasdasdaksdjhasklfhjaljsdh akjhd akljhfkjhs",
  "panNo": "1234564789",
  "phases": [
    {
      "phase": 1,
      "amount": 100
    },
    {
      "phase": 2,
      "amount": 200
    },
    {
      "phase": 3,
      "amount": 300 
    },
    {
      "phase": 4,
      "amount": 400
    }
  ]
}

###

GET http://localhost:8080/api/trade
accept: application/json
content-type: application/json

###

GET http://localhost:8080/api/trade/67a90364bc059f96106cd2c0
accept: application/json
content-type: application/json

###

GET http://localhost:8080/api/trade/asked
cookie: access_token={{login1.response.body.$.accessToken}}
accept: application/json
content-type: application/json

###

GET http://localhost:8080/api/trade/donated
cookie: access_token={{login2.response.body.$.accessToken}}
accept: application/json
content-type: application/json

###

PUT http://localhost:8080/api/trade/67a9acefe9ce9245de3c2798/pledge
cookie: access_token={{login2.response.body.$.accessToken}}
accept: application/json
content-type: application/json

###

PUT http://localhost:8080/api/trade/67a9acefe9ce9245de3c2798/completePhase/5
cookie: access_token={{login1.response.body.$.accessToken}}
accept: application/json
content-type: application/json

###
