###
# @name getUsers

GET http://localhost:8080/api/user/
accept: application/json
content-type: application/json

###
# @name getUsersById

GET http://localhost:8080/api/user/67a8b3cc034cd653f080fecb
accept: application/json
content-type: application/json

###
# @name register

POST http://localhost:8080/api/user/register
accept: application/json
content-type: application/json

{
  "panNo": "210893713894723",
  "name": "Anshu Gahire",
  "email": "test2@test.com",
  "password": "test2",
  "phNo": "3298489",
  "panImg": "askdhasjd",
  "profilePic": "asldkjas",
  "bankName": "Global IME Bank",
  "accNo": "39842398472398",
  "accName": "Anshu Gahire"
}

###
# @name login

POST http://localhost:8080/api/user/login
accept: application/json
content-type: application/json

{
  "panNo": "2108937138904723",
  "password": "test"
}
